services:
  - type: web
    name: jarvis-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ENABLED_TOOLS
        value: run_code,weather,scrape,file_analysis,web_search
      - key: AUTH_MODE
        value: google
      - key: MEMORY_PROVIDER
        value: local
      - key: ENABLE_LOGS
        value: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
    autoDeploy: true
    region: oregon
    healthCheckPath: /health

